### ISSUE TITLE
Update Seat Plugins

### ISSUE THREAD

**Issue by Pr3ciseD34th** [herpaderpaldent/seat-notifications#76]
How can i update Seat Plugins i cannot figure this out. Anyone got an idea?

**Comment by warlof** [comment]
You should have everything you need here https://eveseat.github.io/docs/upgrading/general/

**Comment by Pr3ciseD34th** [comment]
Did allready try this it does not update community packages. Any other way to do this?

**Comment by Pr3ciseD34th** [comment]
The package Seat Groups and Seat notifications wont ever update for me

**Comment by herpaderpaldent** [comment]
Join slack for support: https://eveseat-slack.herokuapp.com/.  I fear you have other issues as well. As soon as you are on slack tell us what other package versions you got
