### ISSUE TITLE
Crash when installing via docker

### ISSUE THREAD

**Issue by Riftr** [herpaderpaldent/seat-notifications#83]
When attempting to install the plugin using my .env file from an instance of Seat installed using the standard script, Seat fails to fully start up. Doing  `docker-compose up -d` completes successfully however Seat itself never becomes available on the usual port. 

After seeing the error below, `docker-compose exec seat-app php artisan migrate` results in there being nothing to do as well.

During startup the following errors occur in the docker logs with this plugin enabled:

> 
> seat-worker    | In ClassLoader.php line 444:
> seat-worker    |
> seat-worker    |   include(/var/www/seat/vendor/composer/../laravel/horizon/src/Events/JobRele
> seat-worker    |   ased.php): failed to open stream: No such file or directory
> seat-worker    |
> seat-worker    |
> seat-worker    | In ClassLoader.php line 444:
> seat-worker    |
> seat-worker    |   include(/var/www/seat/vendor/composer/../laravel/framework/src/Illuminate/Q
> seat-worker    |   ueue/FailingJob.php): failed to open stream: No such file or directory
> seat-worker    |
> seat-worker    |
> seat-worker    |
> seat-worker    | In ClassLoader.php line 444:
> seat-worker    |
> seat-worker    |   include(/var/www/seat/vendor/composer/../laravel/horizon/src/Events/WorkerP
> seat-worker    |   rocessRestarting.php): failed to open stream: No such file or directory
> seat-worker    |
> seat-worker    |

Further on.. 

> seat-app       | Installing and updating plugins...
> seat-app       | Installing plugins: herpaderpaldent/seat-notifications
> seat-cron exited with code 137
> seat-worker exited with code 137
> seat-nginx exited with code 137

**Comment by herpaderpaldent** [comment]
Any of the logs from `seat-worker` do not relate to the installation of any plugin with eveseat, as the installation is done inside the `seat-app` container.

> seat-worker | include(/var/www/seat/vendor/composer/../laravel/horizon/src/Events/JobRele
> seat-worker | ased.php): failed to open stream: No such file or directory
is an issue of the Laravel/Horizon and is on a framework level, probably due to the missing src files during the composer up

Would be interesting to see what's after `seat-app | Installing plugins: herpaderpaldent/seat-notifications` ... if your Host does not have enough ram this would lead into an issue as well, as composer requires lots of memory for the installation of packages. 

Sofar nothing to do with seat-notifications.

**Comment by Riftr** [comment]
> Any of the logs from `seat-worker` do not relate to the installation of any plugin with eveseat, as the installation is done inside the `seat-app` container.

If there is another log please point me in the right direction and I'll provide them. These errors don't occur with seat-notifications disabled however.

> Would be interesting to see what's after `seat-app | Installing plugins: herpaderpaldent/seat-notifications` ... if your Host does not have enough ram this would lead into an issue as well, as composer requires lots of memory for the installation of packages.

> seat-app       | Installing plugins: herpaderpaldent/seat-notifications
> seat-cron exited with code 137
> seat-worker exited with code 137
> seat-nginx exited with code 137

Here we see everything exiting right after seat-notifications is installed.

Here is the rest immediately after:

> seat-cron      | mysqld is alive
> seat-worker    | mysqld is alive
> seat-cron      | crond: crond (busybox 1.31.1) started, log level 7
> seat-cron      | crond: USER www-data pid   8 cmd php /var/www/seat/artisan schedule:run
> seat-cron      | Running scheduled command: '/usr/local/bin/php' 'artisan' esi:update:esistatus > '/dev/null' 2>&1
> seat-worker    | Horizon started successfully.
> seat-worker    | [2020-04-30 07:01:05] Processing: Seat\Eveapi\Jobs\Skills\Character\Skills
> seat-worker    | [2020-04-30 07:01:05] Processing: Seat\Eveapi\Jobs\Status\Esi
> seat-worker    | [2020-04-30 07:01:05] Processing: Seat\Eveapi\Jobs\Skills\Character\Queue
> seat-worker    | [2020-04-30 07:01:05] Processing: Seat\Eveapi\Jobs\Universe\Structures
> seat-worker    | [2020-04-30 07:01:05] Processed:  Seat\Eveapi\Jobs\Universe\Structures
> seat-worker    | [2020-04-30 07:01:05] Processing: Seat\Eveapi\Jobs\Wallet\Character\Balance
> seat-worker    | [2020-04-30 07:01:06] Processed:  Seat\Eveapi\Jobs\Status\Esi
> seat-worker    | [2020-04-30 07:01:06] Processing: Seat\Eveapi\Jobs\Wallet\Character\Journal
> seat-worker    | [2020-04-30 07:01:06] Processed:  Seat\Eveapi\Jobs\Skills\Character\Queue
> seat-worker    | [2020-04-30 07:01:06] Processing: Seat\Eveapi\Jobs\Wallet\Character\Transactions
> seat-worker    | [2020-04-30 07:01:07] Processed:  Seat\Eveapi\Jobs\Wallet\Character\Balance
> seat-worker    | [2020-04-30 07:01:07] Processing: Seat\Eveapi\Jobs\Assets\Character\Assets
> seat-worker    | [2020-04-30 07:01:07] Processed:  Seat\Eveapi\Jobs\Skills\Character\Skills
> seat-worker    | [2020-04-30 07:01:07] Processing: Seat\Eveapi\Jobs\Bookmarks\Character\Bookmarks
> seat-worker    | [2020-04-30 07:01:08] Processed:  Seat\Eveapi\Jobs\Wallet\Character\Journal
> seat-redis     | 1:M 30 Apr 2020 07:01:09.082 * 100 changes in 300 seconds. Saving...
> seat-redis     | 1:M 30 Apr 2020 07:01:09.087 * Background saving started by pid 13
> seat-redis     | 13:C 30 Apr 2020 07:01:09.699 * DB saved on disk
> seat-redis     | 13:C 30 Apr 2020 07:01:09.712 * RDB: 0 MB of memory used by copy-on-write
> seat-worker    | [2020-04-30 07:01:08] Processing: Seat\Eveapi\Jobs\Calendar\Events
> seat-worker    | [2020-04-30 07:01:08] Processed:  Seat\Eveapi\Jobs\Wallet\Character\Transactions
> seat-worker    | [2020-04-30 07:01:08] Processing: Seat\Eveapi\Jobs\Character\Info
> seat-redis     | 1:M 30 Apr 2020 07:01:09.790 * Background saving terminated with success"

And then right after this is my attempt to connect to it with my web browser:

> seat-nginx     | 2020/04/30 07:01:09 [error] 10#10: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: ${nginx_host}, request: "GET /queue/short-status HTTP/1.0", upstream: "fastcgi://172.18.0.7:9000", host: "seat.inextremis.co", referrer: "https://seat.inextremis.co/configuration/access/roles"
> seat-nginx     | 172.18.0.1 - - [30/Apr/2020:07:01:09 +0000] "GET /queue/short-status HTTP/1.0" 502 174 "https://seat.inextremis.co/configuration/access/roles" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0" "<my ip address>"

**Comment by herpaderpaldent** [comment]
Really only output the seat-app container. As for the installation of the plugin and where the code lives that's the container you are interested in. 
Any ohter issues you have be it in the cgi (nginx) or redis does have nothing (0) to do with the package installation.
